name: deploy_frontend
# Deploys when push made from frontend folder

on:
  push:
    branches: [master]
    paths:
      - "frontend/**" #the name of the folder

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch --account-name azureresumefaiz --auth-mode key -d '$web' -s frontend/
      - name: Purge CDN endpoint
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az cdn endpoint purge --content-paths  "/*" --profile-name "azureresumefaiz" --name "azureresumefaiz" --resource-group "azureresume-rg"

      # Azure logout
      - name: logout
        run: |
          az logout
        if: always()
